### PR TITLE
Add Mailcatcher as an install option

### PR DESCRIPTION
**Pull request by raamdev**
See websharks/ubuntu-bootstrap#4

### CODE REVIEW

**Comment by raamdev** [comment]
@jaswsinc This is in progress, not ready to merge. I just wanted to push my work thus far.

---

I based my work so far on how [VVV sets up Mailcatcher](https://github.com/Varying-Vagrant-Vagrants/VVV/blob/b26f070df0993712ce4c30680777d82ac41fcd09/provision/provision.sh#L457-L508), but the following two lines in the new routine seem to hang indefinitely. I haven't been able to figure out why:

```
    /usr/bin/env rvm default@mailcatcher --create do gem install mailcatcher --no-rdoc --no-ri
    /usr/bin/env rvm wrapper default@mailcatcher --no-prefix mailcatcher catchmail
```

Other TODOs:
- Test that this works as part of `sudo /bootstrap/src/installer`
- After installing Mailcatcher, configure PHP so that it uses Mailcatcher 
- ...?

**Comment by raamdev** [comment]
A little bit of progress: I was able to get Mailcatcher installed by switching to root (`sudo su`) and then running all the commands in `src/setups/mailcatcher`. It seems odd to me that running the same commands as part of `sudo /bootstrap/src/installer` would have problems... not sure if I'm missing something.

**Comment by jaswrks** [comment]
Referencing another project that seems to be an improved variation of MailCatcher and easier to install. https://github.com/mailhog/MailHog ~ I haven't used this yet myself.

**Comment by jaswrks** [comment]
@raamdev I'm adding MailHog to the WSUB. Coming in the next release. See: https://github.com/websharks/ubuntu-bootstrap/pull/10

## Some things to note about MailHog

### Upcoming Release
- Now automatically disabling HSTS whenever the installer runs on a VM. Since browsers like Chrome will lock-onto `https://` only with this enabled, it was impossible to access any development tools over the `http://` protocol; e.g., MailHog. If you install this latest version of the Ubuntu Bootstrap on a `.vm` domain that you have used in the past, **be sure to follow these instructions**. See: http://classically.me/blogs/how-clear-hsts-settings-major-browsers. For instance, remove the `my.vm` or any other `.vm` domains from your HSTS cache. In Google Chrome you can do this from: `chrome://net-internals/#hsts`
- Adding [MailHog](https://github.com/mailhog/MailHog) installation directive: `CFG_INSTALL_MAILHOG`. For VMs, this is now on by default. Instead of installing Postfix, MailHog is now installed as a recommended default. With MailHog running, all outgoing mail sent via PHP scripts (regardless of destination) will instead be sent to a test mailbox that can be accessed in the sandbox UI here: http://my.vm:8025. **Note:** If you are unable to access that location, see the note above about clearing HSTS first. The http://my.vm:8025 URL is available only over `http://`.

**UPDATE:** Now available in: https://github.com/websharks/ubuntu-bootstrap/releases/tag/160501

**Comment by raamdev** [comment]
MailHog looks great to me. :-) Thanks!

**Pull request closed without merging**
